### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by lxjlu** [RoboticExplorationLab/ALGAMES.jl#1]
Hi, l am new guy of julia. When i copy the Installation guide into the julia REPL, the first one work well. The second one (ALGAMES.jl) says "ERROR: GitError(Code:ERROR, Class:Submodule, cannot get submodules without a working tree) ".  Is there a problem with my operation or is there a dependency but not installed?

**Comment by simon-lc** [comment]
Hi, I updated the Readme with a new command that should be working, thanks for reaching out !

**Comment by lxjlu** [comment]
It works. Thanks!
